# Generated by Django 5.1.4 on 2024-12-27 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['Date_Submitted', '-Rating'], 'permissions': [('can_create_review', 'Can create a review'), ('can_edit_review,', 'Can edit a review'), ('can_view_review', 'Can view reviews')]},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='date_submitted',
            new_name='Date_Submitted',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_content',
            new_name='Review_Content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='volunteer',
            new_name='Volunteer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='Sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='Rating',
            field=models.IntegerField(help_text='Rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
