# Generated by Django 5.1.4 on 2024-12-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Sentiment',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
