# Generated by Django 5.1.4 on 2024-12-27 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating')),
                ('department', models.CharField(help_text='Department', max_length=50)),
                ('review_content', models.TextField(help_text='Your Review')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_submitted', '-rating'],
                'permissions': [('can_create_review', 'Can create a review'), ('can_edit_review,', 'Can edit a review'), ('can_view_review', 'Can view reviews')],
            },
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_fname', models.CharField(help_text='First Name', max_length=50)),
                ('vol_lname', models.CharField(help_text='Last Name', max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
