# Generated by Django 5.1.4 on 2024-12-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Volunteer_First_Name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='Volunteer_Last_Name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Sentiment',
            field=models.TextField(editable=False),
        ),
    ]
